ARG BASE_IMAGE=ubuntu
FROM ${BASE_IMAGE}:26.04

ENV DEBIAN_FRONTEND=noninteractive

ARG USE_MIRRORS=true

RUN if [ "$USE_MIRRORS" = "true" ]; then \
      find /etc/apt -maxdepth 2 -type f \( -name '*.sources' -o -name sources.list \) \
        -exec sed -i -E \
          's#https?://(archive|security|ports).ubuntu.com/ubuntu(-ports)?#http://mirrors.ustc.edu.cn/ubuntu#g' \
          {} + ; \
    fi

RUN apt-get update && apt-get install -y --no-install-recommends \
      cmake extra-cmake-modules \
      qt6-base-dev qt6-base-dev-tools qt6-declarative-dev qt6-wayland-dev \
      libplasma-dev libplasmaactivities-dev libplasmaactivitiesstats-dev plasma-workspace-dev kwayland-dev \
      libkf6config-dev libkf6coreaddons-dev libkf6guiaddons-dev libkf6dbusaddons-dev \
      libkf6declarative-dev libkf6itemmodels-dev libkf6xmlgui-dev libkf6iconthemes-dev \
      libkf6kio-dev libkf6i18n-dev libkf6notifications-dev \
      libkf6newstuff-dev libkf6archive-dev libkf6globalaccel-dev \
      libkf6crash-dev libkf6windowsystem-dev libkf6package-dev libkf6svg-dev \
      plasma-wayland-protocols libwayland-dev \
      liblayershellqtinterface-dev \
      gettext build-essential git pkgconf file && \
    rm -rf /var/lib/apt/lists/*
