ARG BASE_IMAGE=archlinux
FROM ${BASE_IMAGE}:latest

ARG USE_MIRRORS=false

RUN if [ "$USE_MIRRORS" = "true" ]; then \
      echo 'Server = https://mirrors.ustc.edu.cn/archlinux/$repo/os/$arch' > /etc/pacman.d/mirrorlist ; \
    fi

RUN pacman -Syu --noconfirm && \
    printf '\n\n' | pacman -S --noconfirm --needed \
      cmake extra-cmake-modules \
      qt6-base qt6-declarative qt6-wayland \
      libplasma plasma-activities plasma-activities-stats plasma-workspace kwayland \
      kconfig kcoreaddons kguiaddons kdbusaddons \
      kdeclarative kitemmodels kxmlgui kiconthemes kio ki18n knotifications \
      knewstuff karchive kpackage kglobalaccel kcrash kwindowsystem ksvg \
      plasma-wayland-protocols wayland \
      layer-shell-qt \
      gcc make gettext git pkgconf zstd && \
    pacman -Scc --noconfirm
